export interface ProductList {
  id: number;
  type: string;
  sku: string | null;
  gtin: string | null;
  name: string;
  published: number;
  isFeatured: number;
  visibilityInCatalog: string;
  shortDescription: string | null;
  description: string | null;
  dateSalePriceStarts: string | null;
  dateSalePriceEnds: string | null;
  taxStatus: string;
  taxClass: string | null;
  inStock: number;
  stock: number;
  lowStockAmount: number | null;
  backordersAllowed: number;
  soldIndividually: number;
  weight: number | null;
  length: number | null;
  width: number | null;
  height: number | null;
  allowCustomerReviews: number;
  purchaseNote: string | null;
  salePrice: number | null;
  regularPrice: number;
  categories: string | null;
  tags: string | null;
  shippingClass: string | null;
  images: string | null;
  downloadLimit: string | null;
  downloadExpiryDays: number | null;
  parent: string | null;
  groupedProducts: string | null;
  upsells: string | null;
  crossSells: string | null;
  externalURL: string | null;
  buttonText: string | null;
  position: number | null;
  brands: string | null;
  attribute1Name: string | null;
  attribute1Value: string | null;
  attribute1Visible: number | null;
  attribute1Global: number | null;
  attribute2Name: string | null;
  attribute2Value: string | null;
  attribute2Visible: number | null;
  attribute2Global: number | null;
  attribute3Name: string | null;
  attribute3Value: string | null;
  attribute3Visible: number | null;
  attribute3Global: number | null;
  attribute4Name: string | null;
  attribute4Value: string | null;
  attribute4Visible: number | null;
  attribute4Global: number | null;
  attribute5Name: string | null;
  attribute5Value: string | null;
  attribute5Visible: number | null;
  attribute5Global: number | null;
  attribute6Name: string | null;
  attribute6Value: string | null;
  attribute6Visible: number | null;
  attribute6Global: number | null;
  attribute7Name: string | null;
  attribute7Value: string | null;
  attribute7Visible: number | null;
  attribute7Global: number | null;
  attribute8Name: string | null;
  attribute8Value: string | null;
  attribute8Visible: number | null;
  attribute8Global: number | null;
  attribute9Name: string | null;
  attribute9Value: string | null;
  attribute9Visible: number | null;
  attribute9Global: number | null;
}

type Product = Omit<ProductList, "id">;

export interface ProductForm {
  products: Product[];
}
