import React, { type ReactNode } from "react";
import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AppProviders from "@/components/AppProviders";
import DefaultLayout from "@/layouts/default";

// Iconify
import "@/assets/iconify-icons/generated-icons.css";

// Image Lightbox
import "lity/dist/lity.css";

// Global CSS
import "./globals.css";

export const metadata: Metadata = {
  title: "Tool",
  description: "Generated by 2H",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <React.StrictMode>
          <AntdRegistry>
            <AppProviders lang="en">
              <DefaultLayout>{children}</DefaultLayout>
            </AppProviders>
          </AntdRegistry>
        </React.StrictMode>
      </body>
    </html>
  );
}
